# ----------------------------
# Mongo Deployment
# ----------------------------

apiVersion: apps/v1          # Deployment API version
kind: Deployment             # Resource type

metadata:
  name: logger-service              # Deployment name

spec:
  replicas: 1                # Run one Mongo Pod

  selector:
    matchLabels:
      app: logger-service           # Select Pods having label app=logger-service

  template:                  # Blueprint for creating Pods
    metadata:
      labels:
        app: logger-service           # Label assigned to created Pods

    spec:
      containers:
        - name: logger-service
          image: "dswayam1013/logger-service:1.0.1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

         

          ports:
            - containerPort: 80  # Logger service listens here
            - containerPort: 5001
            - containerPort: 50001
             

---

# ----------------------------
# Mongo Service
# ----------------------------

apiVersion: v1               # Core API
kind: Service                # Kubernetes Service

metadata:
  name: logger-service

spec:

  selector:
    app: logger-service               # Forward traffic to Pods having app=logger-service

  ports:
    - protocol: TCP
      name: web-port
      port: 80         # Service Port
      targetPort: 80 
    - protocol: TCP
      name: rpc-port
      port: 5001         # Service Port
      targetPort: 5001  
    - protocol: TCP
      name: grpc-port
      port: 50001         # Service Port
      targetPort: 50001     # Pod Port