# ----------------------------
# Mongo Deployment
# ----------------------------

apiVersion: apps/v1          # Deployment API version
kind: Deployment             # Resource type

metadata:
  name: mongo                # Deployment name

spec:
  replicas: 1                # Run one Mongo Pod

  selector:
    matchLabels:
      app: mongo             # Select Pods having label app=mongo

  template:                  # Blueprint for creating Pods
    metadata:
      labels:
        app: mongo           # Label assigned to created Pods

    spec:
      containers:
        - name: mongo
          image: "mongo:4.2.17-bionic"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

          env:
            - name: MONGO_INITDB_DATABASE
              value: "logs"

            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"

            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"

          ports:
            - containerPort: 27017   # Mongo listens here

---

# ----------------------------
# Mongo Service
# ----------------------------

apiVersion: v1               # Core API
kind: Service                # Kubernetes Service

metadata:
  name: mongo

spec:

  selector:
    app: mongo               # Forward traffic to Pods having app=mongo

  ports:
    - protocol: TCP
      name: main-port
      port: 27017            # Service Port
      targetPort: 27017      # Pod Port